version: '3'
services:
  desafio-backend-ruby-redis:
    container_name: desafio-backend-ruby-redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - desafio-backend-ruby-network
  desafio-backend-ruby:
    container_name: desafio-backend-ruby
    build: .
    command: bundle exec rails s -p 9090 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "9090:9090"
    depends_on:
      - desafio-backend-ruby-redis
    networks:
      - desafio-backend-ruby-network
networks:
  desafio-backend-ruby-network:
    driver: bridge
